name: Build application

on: [pull_request, push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build --no-daemon
  
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17 # Build is broken with JDK 20
          cache: gradle
      - run: ./gradlew.bat build --no-daemon
